-- Alter staff_commitments to add actual completion tracking columns
ALTER TABLE staff_commitments 
ADD COLUMN IF NOT EXISTS actual_deal INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_calls INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_crm_lead INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_crm_car_post INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_olx_car_post INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_fb_marketplace INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_reel_creation INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_visits INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_add_new_dealer_list INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS actual_add_new_club_member INTEGER NOT NULL DEFAULT 0;
